# === FILE: ghostforge_writer.py ===
# 🔥 The GhostForge - writes Python modules automatically if missing.

import os

def generate_new_module(module_name):
    filename = f"{module_name}.py"
    if os.path.exists(filename):
        print(f"[GhostForge] 📝 Module {filename} already exists.")
        return
    # Write a starter file
    with open(filename, "w") as f:
        f.write(f"# === FILE: {filename} ===\n")
        f.write(f"# 🚀 Auto-generated by GhostForge\n")
        f.write(f"def {module_name}_placeholder():\n")
        f.write(f"    print('[{module_name}] 🚀 Running placeholder logic.')\n")
    print(f"[GhostForge] 🔥 Created new module: {filename}")